# logback-spring.xml 日志配置管理
logging:
  level:
    root: info
    com.emirio.configuration: info
  file:
    max-size: 10MB
    max-history: 3
    total-size-cap: 100MB
    clean-history-on-start: true